### ISSUE TITLE
unable to add overlay image

### ISSUE THREAD

**Issue by 11abhishek11** [AnupKumarPanwar/ScratchView#2]
![Screen Shot 2019-09-05 at 5 50 01 PM](https://user-images.githubusercontent.com/45003000/64341283-a305f000-d005-11e9-8703-98314d4f6983.png)

Unable to add any overlay image to widget. See my xml below:

<com.anupkumarpanwar.scratchview.ScratchView
        android:id="@+id/scratch_view"
        android:layout_width="320dp"
        android:layout_height="320dp"
        android:visibility="visible"
        app:layout_constraintStart_toStartOf="@+id/scratchcard"
        app:layout_constraintEnd_toEndOf="@+id/scratchcard"
        app:layout_constraintTop_toTopOf="@+id/scratchcard"
        app:layout_constraintBottom_toBottomOf="@+id/scratchcard"
        app:overlay_image="@drawable/ic_close"
        app:tile_mode="CLAMP"
        app:overlay_width="150dp"
        app:overlay_height="150dp"
        />

**Comment by AnupKumarPanwar** [comment]
Please upgrade to version 1.3 of the library.
